device: mps
n_epochs: 5
batch_size: 16
learning_rate: 0.0002
weight_decay: 0.0002
PATH_SAVE: ./ckpt
model_name: google/vit-base-patch32-224-in21k
default_data_transform: True 

patch_size: 32
dim: 1024
depth: 6
heads: 8
mlp_dim: 2048
dropout: 0.1
emb_dropout: 0.1